// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkrldcnjtfpwuumausgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrcmxkY25qdGZwd3V1bWF1c2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTAyMzgsImV4cCI6MjA2NzIyNjIzOH0.8D0j5YJIBJMwi1vD5nkA6-uPcVpg9kjHXtXh0SOhoLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});